import { Student } from "@/app/components/students/types/studentType";

export const dummyStudents: Student[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    username: "alicej",
    matricNo: "MAT001",
    department: "Computer Science",
    course: "Web Development",
    score: 85,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    username: "bobsmith",
    matricNo: "MAT002",
    department: "Mechanical Engineering",
    course: "Thermodynamics",
    score: 72,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: "3",
    name: "Catherine Lee",
    email: "catherine.lee@example.com",
    username: "cathlee",
    matricNo: "MAT003",
    department: "Electrical Engineering",
    course: "Circuits",
    score: 64,
    grade: "B",
    pictureUrl: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: "4",
    name: "David Green",
    email: "david.green@example.com",
    username: "dgreen",
    matricNo: "MAT004",
    department: "Business Administration",
    course: "Marketing",
    score: 58,
    grade: "C",
    pictureUrl: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: "5",
    name: "Ella Brown",
    email: "ella.brown@example.com",
    username: "ellab",
    matricNo: "MAT005",
    department: "Computer Science",
    course: "AI Fundamentals",
    score: 91,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "6",
    name: "Frank Adams",
    email: "frank.adams@example.com",
    username: "franka",
    matricNo: "MAT006",
    department: "Civil Engineering",
    course: "Structural Analysis",
    score: 47,
    grade: "D",
    pictureUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: "7",
    name: "Grace Turner",
    email: "grace.turner@example.com",
    username: "gracet",
    matricNo: "MAT007",
    department: "Biology",
    course: "Genetics",
    score: 76,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: "8",
    name: "Henry White",
    email: "henry.white@example.com",
    username: "henryw",
    matricNo: "MAT008",
    department: "Physics",
    course: "Quantum Mechanics",
    score: 69,
    grade: "B",
    pictureUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: "9",
    name: "Isabella Davis",
    email: "isabella.davis@example.com",
    username: "isabellad",
    matricNo: "MAT009",
    department: "Economics",
    course: "Microeconomics",
    score: 82,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: "10",
    name: "Jack Miller",
    email: "jack.miller@example.com",
    username: "jackm",
    matricNo: "MAT010",
    department: "Mathematics",
    course: "Linear Algebra",
    score: 55,
    grade: "C",
    pictureUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: "11",
    name: "Karen Young",
    email: "karen.young@example.com",
    username: "kareny",
    matricNo: "MAT011",
    department: "Chemistry",
    course: "Organic Chemistry",
    score: 95,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: "12",
    name: "Liam Scott",
    email: "liam.scott@example.com",
    username: "liams",
    matricNo: "MAT012",
    department: "Political Science",
    course: "Public Policy",
    score: 61,
    grade: "B",
    pictureUrl: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: "13",
    name: "Mia Walker",
    email: "mia.walker@example.com",
    username: "miaw",
    matricNo: "MAT013",
    department: "Computer Science",
    course: "Data Structures",
    score: 88,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: "14",
    name: "Noah Thompson",
    email: "noah.thompson@example.com",
    username: "noaht",
    matricNo: "MAT014",
    department: "History",
    course: "World History",
    score: 44,
    grade: "D",
    pictureUrl: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: "15",
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    username: "oliviam",
    matricNo: "MAT015",
    department: "Psychology",
    course: "Cognitive Psychology",
    score: 79,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: "16",
    name: "Paul Anderson",
    email: "paul.anderson@example.com",
    username: "paula",
    matricNo: "MAT016",
    department: "Sociology",
    course: "Social Theory",
    score: 68,
    grade: "B",
    pictureUrl: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: "17",
    name: "Quinn Harris",
    email: "quinn.harris@example.com",
    username: "quinnh",
    matricNo: "MAT017",
    department: "Law",
    course: "Constitutional Law",
    score: 73,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: "18",
    name: "Ryan King",
    email: "ryan.king@example.com",
    username: "ryank",
    matricNo: "MAT018",
    department: "Architecture",
    course: "Urban Design",
    score: 59,
    grade: "C",
    pictureUrl: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: "19",
    name: "Sophia Wilson",
    email: "sophia.wilson@example.com",
    username: "sophiaw",
    matricNo: "MAT019",
    department: "Philosophy",
    course: "Ethics",
    score: 85,
    grade: "A",
    pictureUrl: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: "20",
    name: "Thomas Baker",
    email: "thomas.baker@example.com",
    username: "thomasb",
    matricNo: "MAT020",
    department: "Computer Science",
    course: "Operating Systems",
    score: 66,
    grade: "B",
    pictureUrl: "https://randomuser.me/api/portraits/men/20.jpg",
  },
];
